
import { Lead, PipelineStage } from './types';

export const mockStages: PipelineStage[] = [
  { id: 'new_lead', name: 'New Lead', color: '#3b82f6', order: 1, icon: 'user-plus' },
  { id: 'contacted', name: 'Contacted', color: '#60a5fa', order: 2, icon: 'phone' },
  { id: 'inspection_scheduled', name: 'Inspection Scheduled', color: '#eab308', order: 3, icon: 'calendar' },
  { id: 'offer_sent', name: 'Offer Sent', color: '#84cc16', order: 4, icon: 'file-text' },
  { id: 'won_deal', name: 'Won Deal', color: '#22c55e', order: 5, icon: 'check-circle', isClosedStage: true },
  { id: 'lost_deal', name: 'Lost Deal', color: '#ef4444', order: 6, icon: 'x-circle', isClosedStage: true }
];

export const mockLeads: Lead[] = [
  {
    id: '1',
    clientName: 'Aisha Bello',
    email: 'aisha.bello@email.com',
    phone: '+23481312345',
    stage: 'new_lead',
    projectInterest: 'Parkview Estate',
    source: 'Website',
    assignedTo: 'Jane Smith',
    priority: 'high',
    dealValue: 25000000,
    notes: [],
    tags: ['House sales'],
    createdAt: '2024-01-15',
    lastActivity: '2024-01-15',
    nextFollowUp: '2024-01-22'
  },
  {
    id: '2',
    clientName: 'Fatima Sanni',
    email: 'fatima.sanni@email.com',
    phone: '+2348021235',
    stage: 'contacted',
    projectInterest: 'Sunrise Homes',
    source: 'Referral',
    assignedTo: 'Mike Johnson',
    priority: 'medium',
    dealValue: 30000000,
    notes: [],
    tags: ['Housing'],
    createdAt: '2024-01-10',
    lastActivity: '2024-01-18',
    nextFollowUp: '2024-01-25'
  },
  {
    id: '3',
    clientName: 'Ibrahim Musa',
    email: 'ibrahim.musa@email.com',
    phone: '+234809112234',
    stage: 'inspection_scheduled',
    projectInterest: 'Harmony Gardens',
    source: 'Social Media',
    assignedTo: 'Sarah Johnson',
    priority: 'high',
    dealValue: 20000000,
    notes: [],
    tags: ['Land sales'],
    createdAt: '2024-01-12',
    lastActivity: '2024-01-20',
    nextFollowUp: '2024-01-24'
  },
  {
    id: '4',
    clientName: 'Rita Okoro',
    email: 'rita.okoro@email.com',
    phone: '+234801234567',
    stage: 'new_lead',
    projectInterest: 'Harmony Gardens',
    source: 'Website',
    assignedTo: 'Tom Wilson',
    priority: 'medium',
    dealValue: 18000000,
    notes: [],
    tags: ['Land sale'],
    createdAt: '2024-01-14',
    lastActivity: '2024-01-19',
    nextFollowUp: '2024-01-26'
  },
  {
    id: '5',
    clientName: 'Stephen Chkete',
    email: 'stephen.chkete@email.com',
    phone: '+234801112234',
    stage: 'contacted',
    projectInterest: 'Legacy Gardens',
    source: 'Cold Call',
    assignedTo: 'Jane Smith',
    priority: 'low',
    dealValue: 35000000,
    notes: [],
    tags: ['Duplex'],
    createdAt: '2024-01-16',
    lastActivity: '2024-01-21',
    nextFollowUp: '2024-01-28'
  },
  {
    id: '6',
    clientName: 'Ibrahim Musa',
    email: 'ibrahim.musa2@email.com',
    phone: '+23480112334',
    stage: 'offer_sent',
    projectInterest: 'Harmony Gardens',
    source: 'Referral',
    assignedTo: 'Mike Johnson',
    priority: 'high',
    dealValue: 22000000,
    notes: [],
    tags: ['Land sales'],
    createdAt: '2024-01-08',
    lastActivity: '2024-01-22',
    nextFollowUp: '2024-01-29'
  }
];
